### ISSUE TITLE
Failing to setup with the following compose

### ISSUE THREAD

**Issue by nipunarora** [mkuchin/docker-registry-web#41]
I use the following docker compose, and am unable to see the repos that are present in the registry. I assume the most basic setup as follows:
```
web:
  container_name: registry-frontend
  image: hyper/docker-registry-web
  ports:
    - "8085:8080"
  links:
    - registry
  environment:
   REGISTRY_HOST: registry
registry:
  container_name: registry
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
  volumes:
    - /data/docker-registry/:/registry

```

When I check for repositories present in the registry service, I can see the repos
I ran the following command:
```
http://<host>:5000/v2/_catalog
```

and got the following result
```
{"repositories":["baseimage","myfirstimage"]}
```
Can anyone help out in figuring out what could be wrong?
