### ISSUE TITLE
How to secure registry and UI

### ISSUE THREAD

**Issue by bergtwvd** [mkuchin/docker-registry-web#46]
I want to set  up a secure registry and front-end (HTTPS/certifactes)/

What needs to be changed in the configuation of the Registry and UI to use HTTPS?

For Registry there are instructions on the docker.com site; but this effects the UI too.
And how to enable https for 8080?

Great additions in 0.1.0 by the way.

Thanks!

**Comment by mkuchin** [comment]
Thanks for question, @bergtwvd. 

The easiest way to secure both registry and frontend is to use Nginx as reverse proxy. 
You can find example configs [here](https://github.com/mkuchin/docker-registry-web/tree/master/examples/nginx-auth-enabled).
To enable HTTPS on nginx you need to change Nginx [config](https://github.com/mkuchin/docker-registry-web/blob/master/examples/nginx-auth-enabled/conf/nginx/default.conf#L13) and  supply `ssl.key` and `ssl.cert` to the nginx container. 

Feel free to ask me if you need further assistance.

**Comment by bergtwvd** [comment]
Thanks, I will have a try.
Any good pointer on how to generate these ssl key/cert for nginx?

**Comment by mkuchin** [comment]
There is a good howto on setting up Nginx with free StartSSL certificate: https://finiteheap.com/webdev/2015/12/06/nginx-startssl-aplus.html

**Comment by bergtwvd** [comment]
On the end I configured the containers such that only port 443 is accessible from the "outside". port 8080 and 5000 are only accessible on the internal registry-net.
The registry auth realm is set to https://<hostname>:443/api/auth

Docker-file:
```
version: '2'
services:
  nginx:
    image: nginx:1.10
    ports:
      - 443:443
    volumes:
       - ./conf/nginx:/etc/nginx/conf.d/:ro
    networks:
      - registry-net
    depends_on:
      - registry
      - registry-web
  registry-web:
    image: hyper/docker-registry-web:v0.1.0
    ports:
      - 8080
    volumes:
       - ./conf/registry-web:/conf:ro
       - ./db:/data
    networks:
      - registry-net
    depends_on:
       - registry
  registry:
    image: registry:2.4.1
    ports:
      - 5000
    volumes:
      - ./conf/registry:/etc/docker/registry:ro
      - ./registry:/var/lib/registry
    networks:
      - registry-net

networks:
  registry-net:
```
