### ISSUE TITLE
stuck at : "Cannot get property 'private' on null object"

### ISSUE THREAD

**Issue by fvigotti** [mkuchin/docker-registry-web#66]
I hasn't been able to run the application, everything works fine entering on the image this is the error
```
2016-10-31 15:46:12,012 [http-bio-8080-exec-10] ERROR web.RepositoryController  - Can't access registry: _catalog?n=100
java.lang.NullPointerException: Cannot get property 'private' on null object
        at docker.registry.web.TokenService.generate(TokenService.groovy:97)
```

with this configuration : 
```yaml
        - name: REGISTRY_URL
          value: "https://registry:5000/v2/"
        - name: REGISTRY_NAME
          value: "registry:5000"
        - name: REGISTRY_AUTH
          value: "token"
        - name: REGISTRY_BASIC_AUTH
          value: "-------base64 user:pass---------"
        - name: REGISTRY_AUTH_TOKEN_REALM
          value: "registry/auth"
        - name: REGISTRY_AUTH_ENABLED
          value: "true"
        - name: REGISTRY_AUTH_TOKEN_ISSUER
          value: "Auth Service"
        - name: REGISTRY_AUTH_TOKEN_SERVICE
          value: "Docker registry"
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/certs/domain.crt"
        - name: REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE
          value: "/certs/domain.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/certs/domain.key"
```
I want only a frontend for a registry with have his own certs and basic auth,
I've tried disabling auth in docker-registry-web and it give me access denied to the registry which is correct, but if I enable *REGISTRY_AUTH_ENABLED=true* it seems to both use the *REGISTRY_BASIC_AUTH* and enable authentication on the frontend *docker-registry-web* which I don't need anyway.. 

but the problem is that nothing works even with *REGISTRY_AUTH_ENABLED=true* I get the error here above..

p.s.
I've tested with both :latest and :v0.1.2
