### ISSUE TITLE
When will info appear in the event page of registry-web?

### ISSUE THREAD

**Issue by KaimingWan** [mkuchin/docker-registry-web#75]
I have installed docker-registry-web successfully and it is really a good project. However, when the user take the push action, I can't see anything in the event page of registry-web. Do I make some mistakes?

**Comment by mkuchin** [comment]
Have you setup notification endpoint in the docker registry?
It should be like this in docker registry config:

```
notifications:
  endpoints:
    - name: listener
      url: http://registry-web:8080/api/notification
      timeout: 500ms
      threshold: 5
      backoff: 1s 
```
