### ISSUE TITLE
use gitlab registry

### ISSUE THREAD

**Issue by glensc** [mkuchin/docker-registry-web#95]
GitLab 8.8 has bundled Docker Container Registry:
https://docs.gitlab.com/ce/user/project/container_registry.html

it's registry configuration is like (`/var/opt/gitlab/registry/config.yml`:
```yml
version: 0.1
...
auth:
  token:
    realm: https://gitlab.example.net/jwt/auth
    service: container_registry
    issuer: omnibus-gitlab-issuer
    rootcertbundle: /var/opt/gitlab/registry/gitlab-registry.crt
```

how to make api calls to such registry server using token auth?

as i understand the token issuer is gitlab (not docker-registry-web), so docker-registry-web needs to obtain token from https://gitlab.example.net/jwt/auth and use token obtained from there against registry server.
