### ISSUE TITLE
curl UNAUTHORIZED

### ISSUE THREAD

**Issue by christopherwoo** [mkuchin/docker-registry-web#99]
### curl UNAUTHORIZED
I run docker-compose.yml in docker-registry-web/examples/auth-enabled, and everything work fine. 
Now I have thoudsands of images to prune, and I choose not to delete them one by one using Web UI. 
I want to try a script contains curl command, but when runing
> ```curl ipaddress:5000/v2/_catalog ``` 

I got 
> ```{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Name":"catalog","Action":"*"}]}]}```

How to get auth and run curl ?

**Comment by christopherwoo** [comment]
### My configuration
```bash
cat conf/registry/config.yml
```


```
version: 0.1

storage:
  filesystem:
    rootdirectory: /registry
  delete:
    enabled: true
    
http:
  addr: 0.0.0.0:5000    

auth:
  token:
    #realm: http://localhost:8080/api/auth
    #service: localhost:5000
    realm: http://ipaddress:8080/api/auth
    service: ipaddress:5000
    issuer: test
    rootcertbundle: /etc/docker/registry/auth.cert

log:
  level: info
  
notifications:
  endpoints:
    - name: listener
      url: http://registry-web:8080/api/notification
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

**ipaddress** is a lan ip address.
